pl -alne 'if($F[5] eq "+"){$l=max(split /\|/,$F[14])-$F[1]}else{$l=$F[2]-min(split /\|/,$F[14])};print "K562\talu\t$l" if $l<1000' K562_alu_hg38.txt >! span.txt
pl -alne 'if($F[5] eq "+"){$l=max(split /\|/,$F[14])-$F[1]}else{$l=$F[2]-min(split /\|/,$F[14])};print "GM12878\talu\t$l" if $l<1000' GM12878_alu_hg38.txt >> span.txt
pl -alne 'if($F[5] eq "+"){$l=max(split /\|/,$F[14])-$F[1]}else{$l=$F[2]-min(split /\|/,$F[14])};print "heart\talu\t$l" if $l<1000' heart_alu_hg38.txt >> span.txt
pl -alne 'if($F[5] eq "+"){$l=max(split /\|/,$F[14])-$F[1]}else{$l=$F[2]-min(split /\|/,$F[14])};print "liver\talu\t$l" if $l<1000' liver_alu_hg38.txt >> span.txt
pl -alne 'if($F[5] eq "+"){$l=max(split /\|/,$F[14])-$F[1]}else{$l=$F[2]-min(split /\|/,$F[14])};print "testis\talu\t$l" if $l<1000' testis_alu_hg38.txt >> span.txt
pl -alne 'if($#F==1){$a{$F[1]}++}else{$n=(split /\|/,$F[16])[0];next if not $a{$n} or $F[13]<2.5 or $F[-1]>50;if($F[5] eq "+"){$l=max(split /\|/,$F[14])-$F[1]}else{$l=$F[2]-min(split /\|/,$F[14])};print "K562\tcoding\t$l"}' $zlab/genome/hg38/gencode.v29.protein_coding.txt K562_assigned_peaks.txt >> span.txt
pl -alne 'if($#F==1){$a{$F[1]}++}else{$n=(split /\|/,$F[16])[0];next if not $a{$n} or $F[13]<2.5 or $F[-1]>50;if($F[5] eq "+"){$l=max(split /\|/,$F[14])-$F[1]}else{$l=$F[2]-min(split /\|/,$F[14])};print "GM12878\tcoding\t$l"}' $zlab/genome/hg38/gencode.v29.protein_coding.txt GM12878_assigned_peaks.txt >> span.txt
pl -alne 'if($#F==1){$a{$F[1]}++}else{$n=(split /\|/,$F[16])[0];next if not $a{$n} or $F[13]<2.5 or $F[-1]>50;if($F[5] eq "+"){$l=max(split /\|/,$F[14])-$F[1]}else{$l=$F[2]-min(split /\|/,$F[14])};print "heart\tcoding\t$l"}' $zlab/genome/hg38/gencode.v29.protein_coding.txt heart_assigned_peaks.txt >> span.txt
pl -alne 'if($#F==1){$a{$F[1]}++}else{$n=(split /\|/,$F[16])[0];next if not $a{$n} or $F[13]<2.5 or $F[-1]>50;if($F[5] eq "+"){$l=max(split /\|/,$F[14])-$F[1]}else{$l=$F[2]-min(split /\|/,$F[14])};print "liver\tcoding\t$l"}' $zlab/genome/hg38/gencode.v29.protein_coding.txt liver_assigned_peaks.txt >> span.txt
pl -alne 'if($#F==1){$a{$F[1]}++}else{$n=(split /\|/,$F[16])[0];next if not $a{$n} or $F[13]<2.5 or $F[-1]>50;if($F[5] eq "+"){$l=max(split /\|/,$F[14])-$F[1]}else{$l=$F[2]-min(split /\|/,$F[14])};print "testis\tcoding\t$l"}' $zlab/genome/hg38/gencode.v29.protein_coding.txt testis_assigned_peaks.txt >> span.txt

pl -alne 'if($#F==1){$a{$F[1]}++}else{$n=(split /\|/,$F[16])[0];next if not $a{$n} or $F[13]<2.5 or $F[-1]>50;if($F[5] eq "+"){$l=max(split /\|/,$F[14])-$F[1]}else{$l=$F[2]-min(split /\|/,$F[14])};print "K562\tcoding\t$l\t$F[-2]"}' $zlab/genome/hg38/gencode.v29.protein_coding.txt K562_assigned_peaks.txt >! span_assign.txt
pl -alne 'if($#F==1){$a{$F[1]}++}else{$n=(split /\|/,$F[16])[0];next if not $a{$n} or $F[13]<2.5 or $F[-1]>50;if($F[5] eq "+"){$l=max(split /\|/,$F[14])-$F[1]}else{$l=$F[2]-min(split /\|/,$F[14])};print "GM12878\tcoding\t$l\t$F[-2]"}' $zlab/genome/hg38/gencode.v29.protein_coding.txt GM12878_assigned_peaks.txt >> span_assign.txt
pl -alne 'if($#F==1){$a{$F[1]}++}else{$n=(split /\|/,$F[16])[0];next if not $a{$n} or $F[13]<2.5 or $F[-1]>50;if($F[5] eq "+"){$l=max(split /\|/,$F[14])-$F[1]}else{$l=$F[2]-min(split /\|/,$F[14])};print "heart\tcoding\t$l\t$F[-2]"}' $zlab/genome/hg38/gencode.v29.protein_coding.txt heart_assigned_peaks.txt >> span_assign.txt
pl -alne 'if($#F==1){$a{$F[1]}++}else{$n=(split /\|/,$F[16])[0];next if not $a{$n} or $F[13]<2.5 or $F[-1]>50;if($F[5] eq "+"){$l=max(split /\|/,$F[14])-$F[1]}else{$l=$F[2]-min(split /\|/,$F[14])};print "liver\tcoding\t$l\t$F[-2]"}' $zlab/genome/hg38/gencode.v29.protein_coding.txt liver_assigned_peaks.txt >> span_assign.txt
pl -alne 'if($#F==1){$a{$F[1]}++}else{$n=(split /\|/,$F[16])[0];next if not $a{$n} or $F[13]<2.5 or $F[-1]>50;if($F[5] eq "+"){$l=max(split /\|/,$F[14])-$F[1]}else{$l=$F[2]-min(split /\|/,$F[14])};print "testis\tcoding\t$l\t$F[-2]"}' $zlab/genome/hg38/gencode.v29.protein_coding.txt testis_assigned_peaks.txt >> span_assign.txt
